add audit ebee backstory
isovalent/ebeedex pull request #52
Opened 2023-05-09 10:35 UTC by xmulligan

2023-05-09 10:36 UTC, xmulligan commented
@qmonnet how did you make all of the other images to make them consistent?

2023-05-09 11:03 UTC, qmonnet commented
> @qmonnet how did you make all of the other images to make them consistent?

As far as I remember:

1. Removed white background, if any
2. Removed margins (`Crop to content` in Gimp)
3. Resize image to have 577 pixels for the longest side (width or heigth, depending on the pictures). 577 is pretty random from my side, just picked the value that was used in several pictures already and seemed OK for full-size while not making the pictures too big.
4. Resize canvas to have the picture square, 577x577 pixels, keeping the picture in the centre.

I wish I was better at Gimp scripting so we could just automate these, but :shrug:.

2023-05-09 11:05 UTC, qmonnet commented
Happy to help if necessary

2023-06-02 10:28 UTC, xmulligan commented on README.md
> +   <td> <img src="" alt="audit bee">
```suggestion
   <td> <img src="images/audit-bee.png" alt="audit bee">
```

2023-06-02 11:02 UTC, qmonnet commented
![audit-ebee](https://github.com/isovalent/ebeedex/assets/17001771/0d105551-9a21-42af-8e22-74f43a060091)

2023-06-05 12:40 UTC, qmonnet requested changes

2023-06-05 12:40 UTC, qmonnet commented on README.md
> +       Backstory:
```suggestion
```

2023-06-06 09:20 UTC, qmonnet approved these changes
Looks all good!
I'd suggest hitting squash-and-merge.

2023-06-06 09:21 UTC, qmonnet commented
Oh wait I can do that myself

2023-06-06 09:22 UTC, merged