add holiday eBee backstory
isovalent/ebeedex pull request #53
Opened 2023-05-09 10:57 UTC by xmulligan

2023-05-09 15:07 UTC, xmulligan commented
I was trying to add a few different traditions, so I added Christmas, Chinese new years, and Hanukkah. I'm happy to add others, those were just the first ones I came up with

2023-05-09 15:10 UTC, qmonnet commented
Oooh so that's why I didn't had the references :sweat_smile: I thought they were all local Christmas traditions :facepalm:. OK never mind me then :)

2023-06-02 10:49 UTC, xmulligan commented on README.md
> +   <td> <img src="" alt="Holiday bee">
```suggestion
   <td> <img src="images/holiday-bee.png" alt="Holiday bee">
```

2023-06-02 11:03 UTC, qmonnet commented
Looks like some of the picture became transparent. Did you do “white to alpha”?

2023-06-05 12:07 UTC, xmulligan commented
I did color to alpha. I thought that was how you removed the white background 😅

2023-06-05 12:40 UTC, qmonnet requested changes

2023-06-05 12:40 UTC, qmonnet commented on README.md
> +       Backstory:
```suggestion
```

2023-06-05 12:40 UTC, qmonnet commented on README.md
> +   <td>#21: Holiday eBee
```suggestion
   <td>#22: Holiday eBee
```

2023-06-05 12:44 UTC, qmonnet commented
> I did color to alpha. I thought that was how you removed the white background sweat_smile

It works for some pictures, but if there's white in the drawing it will remove it, too. I'm using the selection tool to select the background only, then turn it to alpha or simply delete the selection. I'm far from being an expert with graphic tools though, so that's just my two pennies. Happy to help for this one if you have the original picture somewhere

2023-06-05 13:48 UTC, xmulligan commented
I pulled the image right from the issue https://github.com/isovalent/ebeedex/issues/43. Would be great if you had a better way to do it :)

2023-06-05 14:11 UTC, xmulligan commented
updated now

2023-06-05 14:16 UTC, qmonnet approved these changes
Looks all good

2023-06-05 14:34 UTC, merged